server:
  port: 4500
  host: localhost

spring:
  application:
    name: api-gateway
  profiles:
    active: dev
  messages:
    basename: i18n/messages
    encoding: UTF-8
  cloud:
    config:
      discovery:
        enabled: true
        service-id: CONFIG
      profile: dev
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB

zuul:
  routes:
    api-provider-product: /open-product/**
  #排除某些路由
  ignored-patterns:
    - /**/product/listForOrder
management:
  security:
    enabled: false