server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dt_o2o?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: microservice-provider-user  #  指定注册到Eureka的应用的名字，建议全部小写
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      hql:
        bulk_id_strategy: org.hibernate.hql.spi.id.inline.InlineIdsOrClauseBulkIdStrategy
      #ddl-auto: update 自动创建|更新|验证数据库表结构
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  ## 参考 https://www.jianshu.com/p/c0cba2546900
  rabbitmq:
    username: zolvces
    password: zolvces
    addresses: 192.168.39.128:5672
    cache:
      connection:
        #       缓存连接模式,默认一个连接,多个channel
        mode: channel
#        多个连接,多个channel
#        mode: connection
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.artisan: DEBUG

